import Link from "next/link";
import "./globals.css";
import Navbar from "../components/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="p-2.5">
        <main>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
